//! Local (custom-endpoint) implementation of the next-command / AI input
//! suggestion request.
//!
//! When the user's active base model is a custom OpenAI-compatible endpoint,
//! next-command predictions are generated by that endpoint directly instead of
//! going to the Warp server's `/ai/generate_input_suggestions`. The engine
//! stays proto/HTTP-neutral (the `local_agent` crate); this module is the thin
//! adapter that turns the suggestion request into a chat completion and parses
//! the reply back.

use ai::api_keys::{ApiKeyManager, CustomEndpoint};
use local_agent::{ChatMessage, LocalEndpointConfig};
use warpui::{AppContext, EntityId, SingletonEntity};

use super::{GenerateAIInputSuggestionsRequest, GenerateAIInputSuggestionsResponseV2};
use crate::ai::llms::LLMPreferences;
use crate::server::server_api::AIApiError;
use crate::workspaces::user_workspaces::TeamScope;

/// Resolves the local endpoint to use for a next-command prediction, or `None`
/// to fall back to the server. Returns a config only when the active base model
/// belongs to one of the user's custom endpoints.
pub(crate) fn resolve_local_input_endpoint(
    scope: &(impl TeamScope + ?Sized),
    ctx: &AppContext,
    terminal_view_id: Option<EntityId>,
) -> Option<LocalEndpointConfig> {
    let active_model_id = LLMPreferences::as_ref(ctx)
        .get_active_base_model(scope, ctx, terminal_view_id)
        .id
        .as_str()
        .to_string();
    pick_custom_endpoint(
        &active_model_id,
        &ApiKeyManager::as_ref(ctx).keys().custom_endpoints,
    )
}

/// Finds the custom endpoint + model whose `config_key` matches the active base
/// model id, skipping endpoints with an empty URL or API key.
pub(crate) fn pick_custom_endpoint(
    active_model_id: &str,
    endpoints: &[CustomEndpoint],
) -> Option<LocalEndpointConfig> {
    if active_model_id.is_empty() {
        return None;
    }
    for endpoint in endpoints {
        if endpoint.url.trim().is_empty() || endpoint.api_key.is_empty() {
            continue;
        }
        for model in &endpoint.models {
            if !model.config_key.is_empty() && model.config_key == active_model_id {
                return Some(LocalEndpointConfig {
                    base_url: endpoint.url.clone(),
                    api_key: endpoint.api_key.clone(),
                    model_slug: model.name.clone(),
                });
            }
        }
    }
    None
}

/// Generates a next-command suggestion against the custom endpoint.
pub(crate) async fn generate_local_input_suggestions(
    request: &GenerateAIInputSuggestionsRequest,
    endpoint: &LocalEndpointConfig,
) -> Result<GenerateAIInputSuggestionsResponseV2, AIApiError> {
    let transcript = build_suggestion_transcript(request);
    let text = local_agent::complete_text(transcript, endpoint.clone())
        .await
        .map_err(map_local_error)?;
    Ok(parse_command_suggestion(&text, request.prefix.as_deref()))
}

fn map_local_error(err: local_agent::LocalAgentError) -> AIApiError {
    AIApiError::Stream {
        stream_type: "local next command",
        source: anyhow::anyhow!(err),
    }
}

/// Builds the chat transcript for a next-command prediction: a system message
/// describing the task and a user message carrying the recent blocks, history,
/// rejected suggestions, and any typed prefix.
pub(crate) fn build_suggestion_transcript(
    request: &GenerateAIInputSuggestionsRequest,
) -> Vec<ChatMessage> {
    let mut system = String::from(
        "You predict the single next shell command the user is most likely to run in their \
         terminal, based on their recent commands and history. Reply with ONLY the command on one \
         line — no explanation, no prose, no markdown, no backticks. If a prefix is given, your \
         command MUST start with that exact prefix.",
    );
    if let Some(context) = request
        .system_context
        .as_deref()
        .filter(|context| !context.is_empty())
    {
        system.push_str("\n\nEnvironment context (JSON):\n");
        system.push_str(context);
    }

    let mut user = String::new();
    if !request.context_messages.is_empty() {
        user.push_str("Recent terminal blocks (oldest first), as JSON:\n");
        for message in &request.context_messages {
            user.push_str(message);
            user.push('\n');
        }
    }
    if !request.history_context.is_empty() {
        user.push_str("\nRelevant command history:\n");
        user.push_str(&request.history_context);
        user.push('\n');
    }
    if !request.rejected_suggestions.is_empty() {
        user.push_str("\nDo NOT suggest any of these already-rejected commands:\n");
        for rejected in &request.rejected_suggestions {
            user.push_str("- ");
            user.push_str(rejected);
            user.push('\n');
        }
    }
    match request
        .prefix
        .as_deref()
        .filter(|prefix| !prefix.is_empty())
    {
        Some(prefix) => {
            user.push_str(&format!(
                "\nThe user has typed this prefix; complete it into a full command that starts \
                 with exactly `{prefix}`:\n{prefix}"
            ));
        }
        None => user.push_str("\nPredict the next command to run."),
    }

    vec![ChatMessage::System(system), ChatMessage::User(user)]
}

/// Parses the model's reply into a response. The model is asked for a bare
/// command; we defensively strip code fences/backticks and take the first
/// real line. When a prefix was requested the command must extend it, else the
/// suggestion is dropped (empty response).
pub(crate) fn parse_command_suggestion(
    model_output: &str,
    prefix: Option<&str>,
) -> GenerateAIInputSuggestionsResponseV2 {
    let Some(command) = extract_command(model_output) else {
        return GenerateAIInputSuggestionsResponseV2::default();
    };
    if let Some(prefix) = prefix.filter(|prefix| !prefix.is_empty())
        && !command.starts_with(prefix)
    {
        return GenerateAIInputSuggestionsResponseV2::default();
    }
    GenerateAIInputSuggestionsResponseV2 {
        commands: vec![command.clone()],
        ai_queries: vec![],
        most_likely_action: command,
    }
}

/// Pulls the first usable command line out of a model reply, tolerating code
/// fences and inline backticks a model might add despite the instructions.
fn extract_command(model_output: &str) -> Option<String> {
    for raw in model_output.lines() {
        let mut line = raw.trim();
        if line.is_empty() {
            continue;
        }
        if let Some(rest) = line.strip_prefix("```") {
            // A fence line, possibly with a language tag (```sh) or, for a
            // one-line ```cmd``` block, the command itself.
            line = rest
                .trim_start_matches("bash")
                .trim_start_matches("sh")
                .trim();
            if line.is_empty() {
                continue;
            }
        }
        let line = line.trim_matches('`').trim();
        if line.is_empty() {
            continue;
        }
        return Some(line.to_string());
    }
    None
}

#[cfg(test)]
#[path = "local_tests.rs"]
mod tests;
